version: '3.7'
services:

  twhapi:
    container_name: twhapi
    build:
      context: .
      dockerfile: Dockerfile
    #command: 'tail -f /dev/null'
    env_file: .env
    volumes:
      - './:/home/twhadm'
      - '/home/twhadm/node_modules'
    ports:
      - "80:80"
    networks:
      - "twhnet"
networks:
  twhnet:
    name: "twhnet"