version: '3.7'
services:

  twhapi:
    container_name: twhapi
    build:
      context: .
      dockerfile: Dockerfile
    #command: 'tail -f /dev/null'
    volumes:
      - './:/home/twhadm'
      # Uncomment to use a profile defined in ~/.aws/credentials
      #- $HOME/.aws/credentials:/home/twhadm/.aws/credentials:ro
    ports:
      - "80:80"
    networks:
      - "twhnet"
networks:
  twhnet:
    name: "twhnet"
