version: '3.7'
services:

  twhapi-test:
    container_name: twhapi-test
    build:
      context: .
      dockerfile: Dockerfile
    #command: 'tail -f /dev/null'
    command: ['pytest']
    volumes:
      - './:/home/twhadm'
      # Uncomment to use a profile defined in ~/.aws/credentials
      #- $HOME/.aws/credentials:/home/twhadm/.aws/credentials:ro
    networks:
      - "twhnet"
networks:
  twhnet:
    name: "twhnet"
