name: LTS Build Trial Containers
on:
  push: 
    branches:
      - trial
  workflow_dispatch:

jobs:
  build-and-publish-dev-qa:
    uses: harvard-lts/ga-reusable-workflows/.github/workflows/BuildTrial.yml@1.0
    secrets: inherit
